services:
  kali-rainfall:
    container_name: rainfall_lab
    build: ./
    volumes:
      - .:/root/rainfall
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Pour garder le conteneur allumé
    stdin_open: true
    tty: true